// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cs.ut.domain;

import cs.ut.domain.Plant;
import cs.ut.domain.PlantIntegrationTest;
import java.util.Iterator;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect PlantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PlantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    @Test
    public void PlantIntegrationTest.testRemove() {
        Plant obj = dod.getRandomPlant();
        Assert.assertNotNull("Data on demand for 'Plant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Plant' failed to provide an identifier", id);
        obj = Plant.findPlant(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Plant' with identifier '" + id + "'", Plant.findPlant(id));
    }
    
}
